const LOREM = {
  champions: [
    'Aatrox',
    'Ekko',
    'Jinx',
    'Miss Fortune',
    'Shen',
    'Varus',
    'Ahri',
    'Elise',
    'Kalista',
    'Mordekaiser',
    'Shyvana',
    'Vayne',
    'Akali',
    'Evelynn',
    'Karma',
    'Morgana',
    'Singed',
    'Veigar',
    'Alistar',
    'Ezreal',
    'Karthus',
    'Nami',
    'Sion',
    'Vel’Koz',
    'Amumu',
    'Fiddlesticks',
    'Kassadin',
    'Nasus',
    'Sivir',
    'Vi',
    'Anivia',
    'Fiora',
    'Katarina',
    'Nautilus',
    'Skarner',
    'Viktor',
    'Annie',
    'Fizz',
    'Kayle',
    'Nidalee',
    'Sona',
    'Vladimir',
    'Ashe',
    'Galio',
    'Kennen',
    'Nocturne',
    'Soraka',
    'Volibear',
    'Aurelion Sol',
    'Gangplank',
    'Kha’Zix',
    'Nunu',
    'Swain',
    'Warwick',
    'Azir',
    'Garen',
    'Kindred',
    'Olaf',
    'Syndra',
    'Wukong',
    'Bard',
    'Gnar',
    'Kled',
    'Orianna',
    'Tahm Kench',
    'Xerath',
    'Blitzcrank',
    'Gragas',
    'Kog’Maw',
    'Pantheon',
    'Taliyah',
    'Zin Zhao',
    'Brand',
    'Graves',
    'LeBlanc',
    'Poppy',
    'Talon',
    'Yasuo',
    'Braum',
    'Hecarim',
    'Lee Sin',
    'Quinn',
    'Taric',
    'Yorick',
    'Caitlyn',
    'Heimerdinger',
    'Leona',
    'Rammus',
    'Teemo',
    'Zac',
    'Camille',
    'Illaoi',
    'Lissandra',
    'Rek’Sai',
    'Thresh',
    'Zed',
    'Cassiopeia',
    'Irelia',
    'Lucian',
    'Renekton',
    'Tristana',
    'Ziggs',
    'Cho’Gath',
    'Ivern',
    'Lulu',
    'Rengar',
    'Trundle',
    'Zilean',
    'Corki',
    'Janna',
    'Lux',
    'Riven',
    'Tryndamere',
    'Zyra',
    'Darius',
    'Jarvan IV',
    'Malphite',
    'Rumble',
    'Twisted Fate',
    'Diana',
    'Jax',
    'Malzahar',
    'Ryze',
    'Twitch',
    'Dr.Mundo',
    'Jayce',
    'Maokai',
    'Sejuani',
    'Udyr',
    'Draven',
    'Jhin',
    'Master Yi',
    'Shaco',
    'Urgot'
  ],
  yasuoLore: [
    'As a child, Yasuo often believed what the others in his village said of him: on the best days, his very existence was an error in judgement; on the worst, he was a mistake that could never be undone.',
    'Like most pain, there was some truth to it.His mother was a widow already raising a young son, when the man who would be Yasuo’s father blew into her life like an autumn wind.And, just like that lonely season, he was gone again before the blanket of Ionian winter settled over the small family.',
    'Even though Yasuo’s older half - brother, Yone, was everything Yasuo was not—respectful, cautious, conscientious—the two were inseparable.When other children teased Yasuo, Yone was there to defend him.But what Yasuo lacked in patience, he made up for in determination.When Yone began his apprenticeship at the village’s renowned sword school, a young Yasuo followed, waiting outside in monsoon rain, until the teachers relented and opened the gates.',
    'Much to the annoyance of his new peers, Yasuo showed natural talent, and became the only student in several generations to catch the attention of Elder Souma, last master of the legendary wind technique.The old man saw Yasuo’s potential, but like trying to bridle a whirlwind, this pupil was known to ignore most teaching.Yone pleaded with his brother to set aside his arrogance, gifting him a maple seed, the school’s highest lesson in humility.The next morning, Yasuo accepted the position as Souma’s apprentice, and personal bodyguard.',
    'When word of the Noxian invasion reached the school, some were inspired by the great stand that had been taken at the Placidium of Navori, and soon the village was bled of the able bodied.Yasuo longed to add his sword to the cause, but even as his classmates and brother left to fight, he was ordered to remain and protect the elders.',
    'The invasion became a war. Finally, one rain - slicked night, the drums of a Noxian march could be heard in the next valley over.Yasuo abandoned his post, foolishly believing he could turn the tide.',
    'But he found no battle—only a raw grave for hundreds of Noxian and Ionian corpses.Something terrible and unnatural had happened here, something that no single blade could have stopped.The land itself seemed tainted by it.',
    'Sobered, Yasuo returned to the school the next day, only to be surrounded by the remaining students, their swords drawn.Elder Souma was dead, and Yasuo found himself accused not only of dereliction, but of murder.He realized the true killer would go unpunished if he did not act quickly, so he fought his way free, though he knew this would all but confirm his apparent guilt.',
    'Now a fugitive in war - torn Ionia, Yasuo sought any clue that might lead him to the murderer.All the while, he was hunted by his former allies, continually forced to fight or die.This was a price he was willing to pay, until he was tracked down by the one he dreaded most—his own brother, Yone.',
    'Bound by honor, they circled each other.When their swords finally met, Yone was no match and, with a single flash of steel, Yasuo cut his brother down.',
    'He begged forgiveness, but Yone’s dying words were of the wind techniques responsible for Elder Souma’s death, and that his brother was the only one who could have known them.Then he fell silent, passing on before he could grant any absolution.',
    'Without master or brother, Yasuo roamed the mountains distraught, drinking away the pain of war and loss, a sword without a sheath.There in the snow, he met Taliyah, a young Shuriman stone mage who had fled the Noxian military.In her, Yasuo saw an unlikely student, and in himself, an even more unlikely teacher.He trained her in the ways of elemental magic, wind shaping stone, embracing at last the teachings of Elder Souma.',
    'Their world changed with rumors of a risen Shuriman god - emperor.Yasuo and Taliyah parted ways, though he gifted her the treasured maple seed, its lesson now learned.As she returned to her native desert sands, Yasuo set out for his own village, determined to put right his mistakes and find his old master’s true killer.',
    'Within the stone walls of the council hall, Elder Souma’s death was revealed to have been an accident, one brought about by the Noxian exile known as Riven—and one for which she felt deep remorse.Even so, Yasuo still could not absolve himself of the choice he had made to abandon his master or, worse yet, how that choice had ultimately led to Yone’s death.',
    'To this day, Yasuo continues to wander the land, his sense of guilt the only thing weighing down the free wind.',
    'Stripped of the faith and conviction that had bolstered her entire life, Riven chose to exile herself, wandering Ionia’s battle-scarred landscape. When she finally returned to the village where she had broken the sword, it was revealed that her self-destructive needs had cost the life of their most revered elder… but where Noxus would certainly have condemned Riven to death for such a crime, Ionia embraced her with forgiveness.'
  ]
}

